name: test-action
on: [push]
jobs:
  start-runner:
    name: Start VPS
    runs-on: ubuntu-latest
    steps:
      - id: start-runner
        uses: osmarks/mb-actions-runner@v1
        with:
          action: unsuspend
          gh-token: ${{ secrets.GH_TOKEN }}
          mb-token: ${{ secrets.MB_TOKEN }}
          mb-secret: ${{ secrets.MB_SECRET }}
          server-id: # to fill in
          # ssh-pubkey: optional
          # uncomment if you don't want a new VPS to be started if the specified one does not exist
          # unsuspend-only: true
  run-action:
    name: Execute thing on runner
    needs: start-runner
    runs-on: # to fill in! must be the same as server-id in other steps
    steps:
      - name: Hello World
        run: echo Hello World!
  stop-runner:
    name: Stop VPS
    needs:
      - start-runner
      - run-action
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: osmarks/mb-actions-runner@v1
        with:
          action: suspend
          gh-token: ${{ secrets.GH_TOKEN }}
          mb-token: ${{ secrets.MB_TOKEN }}
          mb-secret: ${{ secrets.MB_SECRET }}
          server-id: # also to fill in