name: example-workflow
on: [push]
jobs:
  start-runner:
    name: Start VPS
    runs-on: ubuntu-latest
    outputs:
      server-id: ${{ steps.start-runner.outputs.server-id }}
    steps:
      - id: start-runner
        uses: osmarks/mb-actions-runner@v1
        with:
          action: start
          gh-token: ${{ secrets.GH_TOKEN }}
          mb-token: ${{ secrets.MB_TOKEN }}
          mb-secret: ${{ secrets.MB_SECRET }}
          # ssh-pubkey: optionally configure this
  run-action:
    name: Execute thing on runner
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.server-id }}
    steps:
      - name: Hello World
        run: echo Hello World!
  stop-runner:
    name: Stop VPS
    needs:
      - start-runner
      - run-action
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: osmarks/mb-actions-runner@v1
        with:
          action: stop
          server-id: ${{ needs.start-runner.outputs.server-id }}
          gh-token: ${{ secrets.GH_TOKEN }}
          mb-token: ${{ secrets.MB_TOKEN }}
          mb-secret: ${{ secrets.MB_SECRET }}